// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializeerrorResponse")
public inline fun errorResponse(block: com.siesque.plantos.proto.admin.v1.ErrorResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ErrorResponse =
  com.siesque.plantos.proto.admin.v1.ErrorResponseKt.Dsl._create(com.siesque.plantos.proto.admin.v1.ErrorResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.ErrorResponse`
 */
public object ErrorResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.ErrorResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.ErrorResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.ErrorResponse = _builder.build()

    /**
     * `.plantos.admin.v1.ErrorCode code = 1;`
     */
    public var code: com.siesque.plantos.proto.admin.v1.ErrorCode
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    public var codeValue: kotlin.Int
      @kotlin.jvm.JvmName("getCodeValue")
        get() = _builder.codeValue
      @kotlin.jvm.JvmName("setCodeValue")
        set(value) {
        _builder.codeValue = value
      }
    /**
     * `.plantos.admin.v1.ErrorCode code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * Optional: request that caused the error
     * ```
     *
     * `string request_type = 3;`
     */
    public var requestType: kotlin.String
      @kotlin.jvm.JvmName("getRequestType")
        get() = _builder.requestType
      @kotlin.jvm.JvmName("setRequestType")
        set(value) {
        _builder.requestType = value
      }
    /**
     * ```
     * Optional: request that caused the error
     * ```
     *
     * `string request_type = 3;`
     */
    public fun clearRequestType() {
      _builder.clearRequestType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.ErrorResponse.copy(block: `com.siesque.plantos.proto.admin.v1`.ErrorResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ErrorResponse =
  `com.siesque.plantos.proto.admin.v1`.ErrorResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

