// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializegetModuleRequest")
public inline fun getModuleRequest(block: com.siesque.plantos.proto.admin.v1.GetModuleRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetModuleRequest =
  com.siesque.plantos.proto.admin.v1.GetModuleRequestKt.Dsl._create(com.siesque.plantos.proto.admin.v1.GetModuleRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Client -> Hub: Request module details
 * ```
 *
 * Protobuf type `plantos.admin.v1.GetModuleRequest`
 */
public object GetModuleRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.GetModuleRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.GetModuleRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.GetModuleRequest = _builder.build()

    /**
     * `int32 module_id = 1;`
     */
    public var moduleId: kotlin.Int
      @kotlin.jvm.JvmName("getModuleId")
        get() = _builder.moduleId
      @kotlin.jvm.JvmName("setModuleId")
        set(value) {
        _builder.moduleId = value
      }
    /**
     * `int32 module_id = 1;`
     */
    public fun clearModuleId() {
      _builder.clearModuleId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.GetModuleRequest.copy(block: `com.siesque.plantos.proto.admin.v1`.GetModuleRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetModuleRequest =
  `com.siesque.plantos.proto.admin.v1`.GetModuleRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

