// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializegetModuleResponse")
public inline fun getModuleResponse(block: com.siesque.plantos.proto.admin.v1.GetModuleResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetModuleResponse =
  com.siesque.plantos.proto.admin.v1.GetModuleResponseKt.Dsl._create(com.siesque.plantos.proto.admin.v1.GetModuleResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * Hub -> Client: Module details
 * ```
 *
 * Protobuf type `plantos.admin.v1.GetModuleResponse`
 */
public object GetModuleResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.GetModuleResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.GetModuleResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.GetModuleResponse = _builder.build()

    /**
     * `.plantos.admin.v1.Module module = 1;`
     */
    public var module: com.siesque.plantos.proto.admin.v1.Module
      @kotlin.jvm.JvmName("getModule")
        get() = _builder.module
      @kotlin.jvm.JvmName("setModule")
        set(value) {
        _builder.module = value
      }
    /**
     * `.plantos.admin.v1.Module module = 1;`
     */
    public fun clearModule() {
      _builder.clearModule()
    }
    /**
     * `.plantos.admin.v1.Module module = 1;`
     * @return Whether the module field is set.
     */
    public fun hasModule(): kotlin.Boolean {
      return _builder.hasModule()
    }

    public val GetModuleResponseKt.Dsl.moduleOrNull: com.siesque.plantos.proto.admin.v1.Module?
      get() = _builder.moduleOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.GetModuleResponse.copy(block: `com.siesque.plantos.proto.admin.v1`.GetModuleResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetModuleResponse =
  `com.siesque.plantos.proto.admin.v1`.GetModuleResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.GetModuleResponseOrBuilder.moduleOrNull: com.siesque.plantos.proto.admin.v1.Module?
  get() = if (hasModule()) getModule() else null

