// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializegetStatisticsResponse")
public inline fun getStatisticsResponse(block: com.siesque.plantos.proto.admin.v1.GetStatisticsResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetStatisticsResponse =
  com.siesque.plantos.proto.admin.v1.GetStatisticsResponseKt.Dsl._create(com.siesque.plantos.proto.admin.v1.GetStatisticsResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * Hub -> Client: Statistics response
 * ```
 *
 * Protobuf type `plantos.admin.v1.GetStatisticsResponse`
 */
public object GetStatisticsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.GetStatisticsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.GetStatisticsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.GetStatisticsResponse = _builder.build()

    /**
     * `int32 zone_id = 1;`
     */
    public var zoneId: kotlin.Int
      @kotlin.jvm.JvmName("getZoneId")
        get() = _builder.zoneId
      @kotlin.jvm.JvmName("setZoneId")
        set(value) {
        _builder.zoneId = value
      }
    /**
     * `int32 zone_id = 1;`
     */
    public fun clearZoneId() {
      _builder.clearZoneId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class StatisticsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .plantos.admin.v1.Statistic statistics = 2;`
     */
     public val statistics: com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, StatisticsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.statisticsList
      )
    /**
     * `repeated .plantos.admin.v1.Statistic statistics = 2;`
     * @param value The statistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addStatistics")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, StatisticsProxy>.add(value: com.siesque.plantos.proto.admin.v1.Statistic) {
      _builder.addStatistics(value)
    }
    /**
     * `repeated .plantos.admin.v1.Statistic statistics = 2;`
     * @param value The statistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignStatistics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, StatisticsProxy>.plusAssign(value: com.siesque.plantos.proto.admin.v1.Statistic) {
      add(value)
    }
    /**
     * `repeated .plantos.admin.v1.Statistic statistics = 2;`
     * @param values The statistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllStatistics")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, StatisticsProxy>.addAll(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.Statistic>) {
      _builder.addAllStatistics(values)
    }
    /**
     * `repeated .plantos.admin.v1.Statistic statistics = 2;`
     * @param values The statistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllStatistics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, StatisticsProxy>.plusAssign(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.Statistic>) {
      addAll(values)
    }
    /**
     * `repeated .plantos.admin.v1.Statistic statistics = 2;`
     * @param index The index to set the value at.
     * @param value The statistics to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setStatistics")
    public operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, StatisticsProxy>.set(index: kotlin.Int, value: com.siesque.plantos.proto.admin.v1.Statistic) {
      _builder.setStatistics(index, value)
    }
    /**
     * `repeated .plantos.admin.v1.Statistic statistics = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearStatistics")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, StatisticsProxy>.clear() {
      _builder.clearStatistics()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.GetStatisticsResponse.copy(block: `com.siesque.plantos.proto.admin.v1`.GetStatisticsResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetStatisticsResponse =
  `com.siesque.plantos.proto.admin.v1`.GetStatisticsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

