// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializegetStatisticsRequest")
public inline fun getStatisticsRequest(block: com.siesque.plantos.proto.admin.v1.GetStatisticsRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetStatisticsRequest =
  com.siesque.plantos.proto.admin.v1.GetStatisticsRequestKt.Dsl._create(com.siesque.plantos.proto.admin.v1.GetStatisticsRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Client -> Hub: Get historical statistics
 * ```
 *
 * Protobuf type `plantos.admin.v1.GetStatisticsRequest`
 */
public object GetStatisticsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.GetStatisticsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.GetStatisticsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.GetStatisticsRequest = _builder.build()

    /**
     * `int32 zone_id = 1;`
     */
    public var zoneId: kotlin.Int
      @kotlin.jvm.JvmName("getZoneId")
        get() = _builder.zoneId
      @kotlin.jvm.JvmName("setZoneId")
        set(value) {
        _builder.zoneId = value
      }
    /**
     * `int32 zone_id = 1;`
     */
    public fun clearZoneId() {
      _builder.clearZoneId()
    }

    /**
     * ```
     * Time range (required)
     * ```
     *
     * `.google.protobuf.Timestamp from = 2;`
     */
    public var from: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getFrom")
        get() = _builder.from
      @kotlin.jvm.JvmName("setFrom")
        set(value) {
        _builder.from = value
      }
    /**
     * ```
     * Time range (required)
     * ```
     *
     * `.google.protobuf.Timestamp from = 2;`
     */
    public fun clearFrom() {
      _builder.clearFrom()
    }
    /**
     * ```
     * Time range (required)
     * ```
     *
     * `.google.protobuf.Timestamp from = 2;`
     * @return Whether the from field is set.
     */
    public fun hasFrom(): kotlin.Boolean {
      return _builder.hasFrom()
    }

    public val GetStatisticsRequestKt.Dsl.fromOrNull: com.google.protobuf.Timestamp?
      get() = _builder.fromOrNull

    /**
     * `.google.protobuf.Timestamp to = 3;`
     */
    public var to: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTo")
        get() = _builder.to
      @kotlin.jvm.JvmName("setTo")
        set(value) {
        _builder.to = value
      }
    /**
     * `.google.protobuf.Timestamp to = 3;`
     */
    public fun clearTo() {
      _builder.clearTo()
    }
    /**
     * `.google.protobuf.Timestamp to = 3;`
     * @return Whether the to field is set.
     */
    public fun hasTo(): kotlin.Boolean {
      return _builder.hasTo()
    }

    public val GetStatisticsRequestKt.Dsl.toOrNull: com.google.protobuf.Timestamp?
      get() = _builder.toOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TypesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Optional: specific statistic types (empty = all)
     * ```
     *
     * `repeated .plantos.admin.v1.StatisticType types = 4;`
     */
     public val types: com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticType, TypesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.typesList
      )
    /**
     * ```
     * Optional: specific statistic types (empty = all)
     * ```
     *
     * `repeated .plantos.admin.v1.StatisticType types = 4;`
     * @param value The types to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addTypes")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticType, TypesProxy>.add(value: com.siesque.plantos.proto.admin.v1.StatisticType) {
      _builder.addTypes(value)
    }/**
     * ```
     * Optional: specific statistic types (empty = all)
     * ```
     *
     * `repeated .plantos.admin.v1.StatisticType types = 4;`
     * @param value The types to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignTypes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticType, TypesProxy>.plusAssign(value: com.siesque.plantos.proto.admin.v1.StatisticType) {
      add(value)
    }/**
     * ```
     * Optional: specific statistic types (empty = all)
     * ```
     *
     * `repeated .plantos.admin.v1.StatisticType types = 4;`
     * @param values The types to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllTypes")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticType, TypesProxy>.addAll(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.StatisticType>) {
      _builder.addAllTypes(values)
    }/**
     * ```
     * Optional: specific statistic types (empty = all)
     * ```
     *
     * `repeated .plantos.admin.v1.StatisticType types = 4;`
     * @param values The types to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllTypes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticType, TypesProxy>.plusAssign(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.StatisticType>) {
      addAll(values)
    }/**
     * ```
     * Optional: specific statistic types (empty = all)
     * ```
     *
     * `repeated .plantos.admin.v1.StatisticType types = 4;`
     * @param index The index to set the value at.
     * @param value The types to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setTypes")
    public operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticType, TypesProxy>.set(index: kotlin.Int, value: com.siesque.plantos.proto.admin.v1.StatisticType) {
      _builder.setTypes(index, value)
    }/**
     * ```
     * Optional: specific statistic types (empty = all)
     * ```
     *
     * `repeated .plantos.admin.v1.StatisticType types = 4;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearTypes")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticType, TypesProxy>.clear() {
      _builder.clearTypes()
    }
    /**
     * `.plantos.admin.v1.GetStatisticsRequest.Aggregation aggregation = 5;`
     */
    public var aggregation: com.siesque.plantos.proto.admin.v1.GetStatisticsRequest.Aggregation
      @kotlin.jvm.JvmName("getAggregation")
        get() = _builder.aggregation
      @kotlin.jvm.JvmName("setAggregation")
        set(value) {
        _builder.aggregation = value
      }
    public var aggregationValue: kotlin.Int
      @kotlin.jvm.JvmName("getAggregationValue")
        get() = _builder.aggregationValue
      @kotlin.jvm.JvmName("setAggregationValue")
        set(value) {
        _builder.aggregationValue = value
      }
    /**
     * `.plantos.admin.v1.GetStatisticsRequest.Aggregation aggregation = 5;`
     */
    public fun clearAggregation() {
      _builder.clearAggregation()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.GetStatisticsRequest.copy(block: `com.siesque.plantos.proto.admin.v1`.GetStatisticsRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetStatisticsRequest =
  `com.siesque.plantos.proto.admin.v1`.GetStatisticsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.GetStatisticsRequestOrBuilder.fromOrNull: com.google.protobuf.Timestamp?
  get() = if (hasFrom()) getFrom() else null

public val com.siesque.plantos.proto.admin.v1.GetStatisticsRequestOrBuilder.toOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTo()) getTo() else null

