// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializegetZoneSettingsRequest")
public inline fun getZoneSettingsRequest(block: com.siesque.plantos.proto.admin.v1.GetZoneSettingsRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetZoneSettingsRequest =
  com.siesque.plantos.proto.admin.v1.GetZoneSettingsRequestKt.Dsl._create(com.siesque.plantos.proto.admin.v1.GetZoneSettingsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.GetZoneSettingsRequest`
 */
public object GetZoneSettingsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.GetZoneSettingsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.GetZoneSettingsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.GetZoneSettingsRequest = _builder.build()

    /**
     * `int32 zone_id = 1;`
     */
    public var zoneId: kotlin.Int
      @kotlin.jvm.JvmName("getZoneId")
        get() = _builder.zoneId
      @kotlin.jvm.JvmName("setZoneId")
        set(value) {
        _builder.zoneId = value
      }
    /**
     * `int32 zone_id = 1;`
     */
    public fun clearZoneId() {
      _builder.clearZoneId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.GetZoneSettingsRequest.copy(block: `com.siesque.plantos.proto.admin.v1`.GetZoneSettingsRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetZoneSettingsRequest =
  `com.siesque.plantos.proto.admin.v1`.GetZoneSettingsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

