// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializegetZoneResponse")
public inline fun getZoneResponse(block: com.siesque.plantos.proto.admin.v1.GetZoneResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetZoneResponse =
  com.siesque.plantos.proto.admin.v1.GetZoneResponseKt.Dsl._create(com.siesque.plantos.proto.admin.v1.GetZoneResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * Hub -> Client: Zone details
 * ```
 *
 * Protobuf type `plantos.admin.v1.GetZoneResponse`
 */
public object GetZoneResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.GetZoneResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.GetZoneResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.GetZoneResponse = _builder.build()

    /**
     * `.plantos.admin.v1.Zone zone = 1;`
     */
    public var zone: com.siesque.plantos.proto.admin.v1.Zone
      @kotlin.jvm.JvmName("getZone")
        get() = _builder.zone
      @kotlin.jvm.JvmName("setZone")
        set(value) {
        _builder.zone = value
      }
    /**
     * `.plantos.admin.v1.Zone zone = 1;`
     */
    public fun clearZone() {
      _builder.clearZone()
    }
    /**
     * `.plantos.admin.v1.Zone zone = 1;`
     * @return Whether the zone field is set.
     */
    public fun hasZone(): kotlin.Boolean {
      return _builder.hasZone()
    }

    public val GetZoneResponseKt.Dsl.zoneOrNull: com.siesque.plantos.proto.admin.v1.Zone?
      get() = _builder.zoneOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.GetZoneResponse.copy(block: `com.siesque.plantos.proto.admin.v1`.GetZoneResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetZoneResponse =
  `com.siesque.plantos.proto.admin.v1`.GetZoneResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.GetZoneResponseOrBuilder.zoneOrNull: com.siesque.plantos.proto.admin.v1.Zone?
  get() = if (hasZone()) getZone() else null

