// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializegetZoneSettingsResponse")
public inline fun getZoneSettingsResponse(block: com.siesque.plantos.proto.admin.v1.GetZoneSettingsResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetZoneSettingsResponse =
  com.siesque.plantos.proto.admin.v1.GetZoneSettingsResponseKt.Dsl._create(com.siesque.plantos.proto.admin.v1.GetZoneSettingsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.GetZoneSettingsResponse`
 */
public object GetZoneSettingsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.GetZoneSettingsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.GetZoneSettingsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.GetZoneSettingsResponse = _builder.build()

    /**
     * `.plantos.admin.v1.ZoneSettings settings = 1;`
     */
    public var settings: com.siesque.plantos.proto.admin.v1.ZoneSettings
      @kotlin.jvm.JvmName("getSettings")
        get() = _builder.settings
      @kotlin.jvm.JvmName("setSettings")
        set(value) {
        _builder.settings = value
      }
    /**
     * `.plantos.admin.v1.ZoneSettings settings = 1;`
     */
    public fun clearSettings() {
      _builder.clearSettings()
    }
    /**
     * `.plantos.admin.v1.ZoneSettings settings = 1;`
     * @return Whether the settings field is set.
     */
    public fun hasSettings(): kotlin.Boolean {
      return _builder.hasSettings()
    }

    public val GetZoneSettingsResponseKt.Dsl.settingsOrNull: com.siesque.plantos.proto.admin.v1.ZoneSettings?
      get() = _builder.settingsOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.GetZoneSettingsResponse.copy(block: `com.siesque.plantos.proto.admin.v1`.GetZoneSettingsResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetZoneSettingsResponse =
  `com.siesque.plantos.proto.admin.v1`.GetZoneSettingsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.GetZoneSettingsResponseOrBuilder.settingsOrNull: com.siesque.plantos.proto.admin.v1.ZoneSettings?
  get() = if (hasSettings()) getSettings() else null

