// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializegetZoneRequest")
public inline fun getZoneRequest(block: com.siesque.plantos.proto.admin.v1.GetZoneRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetZoneRequest =
  com.siesque.plantos.proto.admin.v1.GetZoneRequestKt.Dsl._create(com.siesque.plantos.proto.admin.v1.GetZoneRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Client -> Hub: Request zone details
 * ```
 *
 * Protobuf type `plantos.admin.v1.GetZoneRequest`
 */
public object GetZoneRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.GetZoneRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.GetZoneRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.GetZoneRequest = _builder.build()

    /**
     * `int32 zone_id = 1;`
     */
    public var zoneId: kotlin.Int
      @kotlin.jvm.JvmName("getZoneId")
        get() = _builder.zoneId
      @kotlin.jvm.JvmName("setZoneId")
        set(value) {
        _builder.zoneId = value
      }
    /**
     * `int32 zone_id = 1;`
     */
    public fun clearZoneId() {
      _builder.clearZoneId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.GetZoneRequest.copy(block: `com.siesque.plantos.proto.admin.v1`.GetZoneRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.GetZoneRequest =
  `com.siesque.plantos.proto.admin.v1`.GetZoneRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

