// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializehello")
public inline fun hello(block: com.siesque.plantos.proto.admin.v1.HelloKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.Hello =
  com.siesque.plantos.proto.admin.v1.HelloKt.Dsl._create(com.siesque.plantos.proto.admin.v1.Hello.newBuilder()).apply { block() }._build()
/**
 * ```
 * Client -> Hub: Initial handshake
 * ```
 *
 * Protobuf type `plantos.admin.v1.Hello`
 */
public object HelloKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.Hello.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.Hello.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.Hello = _builder.build()

    /**
     * ```
     * "1.0"
     * ```
     *
     * `string protocol_version = 1;`
     */
    public var protocolVersion: kotlin.String
      @kotlin.jvm.JvmName("getProtocolVersion")
        get() = _builder.protocolVersion
      @kotlin.jvm.JvmName("setProtocolVersion")
        set(value) {
        _builder.protocolVersion = value
      }
    /**
     * ```
     * "1.0"
     * ```
     *
     * `string protocol_version = 1;`
     */
    public fun clearProtocolVersion() {
      _builder.clearProtocolVersion()
    }

    /**
     * ```
     * Client app version
     * ```
     *
     * `string client_version = 2;`
     */
    public var clientVersion: kotlin.String
      @kotlin.jvm.JvmName("getClientVersion")
        get() = _builder.clientVersion
      @kotlin.jvm.JvmName("setClientVersion")
        set(value) {
        _builder.clientVersion = value
      }
    /**
     * ```
     * Client app version
     * ```
     *
     * `string client_version = 2;`
     */
    public fun clearClientVersion() {
      _builder.clearClientVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.Hello.copy(block: `com.siesque.plantos.proto.admin.v1`.HelloKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.Hello =
  `com.siesque.plantos.proto.admin.v1`.HelloKt.Dsl._create(this.toBuilder()).apply { block() }._build()

