// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializelistModulesRequest")
public inline fun listModulesRequest(block: com.siesque.plantos.proto.admin.v1.ListModulesRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ListModulesRequest =
  com.siesque.plantos.proto.admin.v1.ListModulesRequestKt.Dsl._create(com.siesque.plantos.proto.admin.v1.ListModulesRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Client -> Hub: Request to list all modules
 * ```
 *
 * Protobuf type `plantos.admin.v1.ListModulesRequest`
 */
public object ListModulesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.ListModulesRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.ListModulesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.ListModulesRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.ListModulesRequest.copy(block: `com.siesque.plantos.proto.admin.v1`.ListModulesRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ListModulesRequest =
  `com.siesque.plantos.proto.admin.v1`.ListModulesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

