// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializelistModulesResponse")
public inline fun listModulesResponse(block: com.siesque.plantos.proto.admin.v1.ListModulesResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ListModulesResponse =
  com.siesque.plantos.proto.admin.v1.ListModulesResponseKt.Dsl._create(com.siesque.plantos.proto.admin.v1.ListModulesResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * Hub -> Client: Module list response
 * ```
 *
 * Protobuf type `plantos.admin.v1.ListModulesResponse`
 */
public object ListModulesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.ListModulesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.ListModulesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.ListModulesResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ModulesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .plantos.admin.v1.Module modules = 1;`
     */
     public val modules: com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Module, ModulesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.modulesList
      )
    /**
     * `repeated .plantos.admin.v1.Module modules = 1;`
     * @param value The modules to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addModules")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Module, ModulesProxy>.add(value: com.siesque.plantos.proto.admin.v1.Module) {
      _builder.addModules(value)
    }
    /**
     * `repeated .plantos.admin.v1.Module modules = 1;`
     * @param value The modules to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignModules")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Module, ModulesProxy>.plusAssign(value: com.siesque.plantos.proto.admin.v1.Module) {
      add(value)
    }
    /**
     * `repeated .plantos.admin.v1.Module modules = 1;`
     * @param values The modules to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllModules")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Module, ModulesProxy>.addAll(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.Module>) {
      _builder.addAllModules(values)
    }
    /**
     * `repeated .plantos.admin.v1.Module modules = 1;`
     * @param values The modules to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllModules")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Module, ModulesProxy>.plusAssign(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.Module>) {
      addAll(values)
    }
    /**
     * `repeated .plantos.admin.v1.Module modules = 1;`
     * @param index The index to set the value at.
     * @param value The modules to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setModules")
    public operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Module, ModulesProxy>.set(index: kotlin.Int, value: com.siesque.plantos.proto.admin.v1.Module) {
      _builder.setModules(index, value)
    }
    /**
     * `repeated .plantos.admin.v1.Module modules = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearModules")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Module, ModulesProxy>.clear() {
      _builder.clearModules()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.ListModulesResponse.copy(block: `com.siesque.plantos.proto.admin.v1`.ListModulesResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ListModulesResponse =
  `com.siesque.plantos.proto.admin.v1`.ListModulesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

