// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializelistZonesRequest")
public inline fun listZonesRequest(block: com.siesque.plantos.proto.admin.v1.ListZonesRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ListZonesRequest =
  com.siesque.plantos.proto.admin.v1.ListZonesRequestKt.Dsl._create(com.siesque.plantos.proto.admin.v1.ListZonesRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Client -> Hub: List all zones
 * ```
 *
 * Protobuf type `plantos.admin.v1.ListZonesRequest`
 */
public object ListZonesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.ListZonesRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.ListZonesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.ListZonesRequest = _builder.build()

    /**
     * ```
     * Optional filter by module
     * ```
     *
     * `optional int32 module_id = 1;`
     */
    public var moduleId: kotlin.Int
      @kotlin.jvm.JvmName("getModuleId")
        get() = _builder.moduleId
      @kotlin.jvm.JvmName("setModuleId")
        set(value) {
        _builder.moduleId = value
      }
    /**
     * ```
     * Optional filter by module
     * ```
     *
     * `optional int32 module_id = 1;`
     */
    public fun clearModuleId() {
      _builder.clearModuleId()
    }
    /**
     * ```
     * Optional filter by module
     * ```
     *
     * `optional int32 module_id = 1;`
     * @return Whether the moduleId field is set.
     */
    public fun hasModuleId(): kotlin.Boolean {
      return _builder.hasModuleId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.ListZonesRequest.copy(block: `com.siesque.plantos.proto.admin.v1`.ListZonesRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ListZonesRequest =
  `com.siesque.plantos.proto.admin.v1`.ListZonesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

