// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializelistZonesResponse")
public inline fun listZonesResponse(block: com.siesque.plantos.proto.admin.v1.ListZonesResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ListZonesResponse =
  com.siesque.plantos.proto.admin.v1.ListZonesResponseKt.Dsl._create(com.siesque.plantos.proto.admin.v1.ListZonesResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * Hub -> Client: Zone list response
 * ```
 *
 * Protobuf type `plantos.admin.v1.ListZonesResponse`
 */
public object ListZonesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.ListZonesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.ListZonesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.ListZonesResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ZonesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .plantos.admin.v1.Zone zones = 1;`
     */
     public val zones: com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Zone, ZonesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.zonesList
      )
    /**
     * `repeated .plantos.admin.v1.Zone zones = 1;`
     * @param value The zones to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addZones")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Zone, ZonesProxy>.add(value: com.siesque.plantos.proto.admin.v1.Zone) {
      _builder.addZones(value)
    }
    /**
     * `repeated .plantos.admin.v1.Zone zones = 1;`
     * @param value The zones to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignZones")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Zone, ZonesProxy>.plusAssign(value: com.siesque.plantos.proto.admin.v1.Zone) {
      add(value)
    }
    /**
     * `repeated .plantos.admin.v1.Zone zones = 1;`
     * @param values The zones to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllZones")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Zone, ZonesProxy>.addAll(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.Zone>) {
      _builder.addAllZones(values)
    }
    /**
     * `repeated .plantos.admin.v1.Zone zones = 1;`
     * @param values The zones to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllZones")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Zone, ZonesProxy>.plusAssign(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.Zone>) {
      addAll(values)
    }
    /**
     * `repeated .plantos.admin.v1.Zone zones = 1;`
     * @param index The index to set the value at.
     * @param value The zones to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setZones")
    public operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Zone, ZonesProxy>.set(index: kotlin.Int, value: com.siesque.plantos.proto.admin.v1.Zone) {
      _builder.setZones(index, value)
    }
    /**
     * `repeated .plantos.admin.v1.Zone zones = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearZones")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Zone, ZonesProxy>.clear() {
      _builder.clearZones()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.ListZonesResponse.copy(block: `com.siesque.plantos.proto.admin.v1`.ListZonesResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ListZonesResponse =
  `com.siesque.plantos.proto.admin.v1`.ListZonesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

