// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializemoduleUpdate")
public inline fun moduleUpdate(block: com.siesque.plantos.proto.admin.v1.ModuleUpdateKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ModuleUpdate =
  com.siesque.plantos.proto.admin.v1.ModuleUpdateKt.Dsl._create(com.siesque.plantos.proto.admin.v1.ModuleUpdate.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.ModuleUpdate`
 */
public object ModuleUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.ModuleUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.ModuleUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.ModuleUpdate = _builder.build()

    /**
     * `int32 module_id = 1;`
     */
    public var moduleId: kotlin.Int
      @kotlin.jvm.JvmName("getModuleId")
        get() = _builder.moduleId
      @kotlin.jvm.JvmName("setModuleId")
        set(value) {
        _builder.moduleId = value
      }
    /**
     * `int32 module_id = 1;`
     */
    public fun clearModuleId() {
      _builder.clearModuleId()
    }

    /**
     * `.plantos.admin.v1.Module module = 2;`
     */
    public var module: com.siesque.plantos.proto.admin.v1.Module
      @kotlin.jvm.JvmName("getModule")
        get() = _builder.module
      @kotlin.jvm.JvmName("setModule")
        set(value) {
        _builder.module = value
      }
    /**
     * `.plantos.admin.v1.Module module = 2;`
     */
    public fun clearModule() {
      _builder.clearModule()
    }
    /**
     * `.plantos.admin.v1.Module module = 2;`
     * @return Whether the module field is set.
     */
    public fun hasModule(): kotlin.Boolean {
      return _builder.hasModule()
    }

    public val ModuleUpdateKt.Dsl.moduleOrNull: com.siesque.plantos.proto.admin.v1.Module?
      get() = _builder.moduleOrNull

    /**
     * `.plantos.admin.v1.ModuleUpdate.ChangeType change_type = 3;`
     */
    public var changeType: com.siesque.plantos.proto.admin.v1.ModuleUpdate.ChangeType
      @kotlin.jvm.JvmName("getChangeType")
        get() = _builder.changeType
      @kotlin.jvm.JvmName("setChangeType")
        set(value) {
        _builder.changeType = value
      }
    public var changeTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getChangeTypeValue")
        get() = _builder.changeTypeValue
      @kotlin.jvm.JvmName("setChangeTypeValue")
        set(value) {
        _builder.changeTypeValue = value
      }
    /**
     * `.plantos.admin.v1.ModuleUpdate.ChangeType change_type = 3;`
     */
    public fun clearChangeType() {
      _builder.clearChangeType()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 4;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 4;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 4;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val ModuleUpdateKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.ModuleUpdate.copy(block: `com.siesque.plantos.proto.admin.v1`.ModuleUpdateKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ModuleUpdate =
  `com.siesque.plantos.proto.admin.v1`.ModuleUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.ModuleUpdateOrBuilder.moduleOrNull: com.siesque.plantos.proto.admin.v1.Module?
  get() = if (hasModule()) getModule() else null

public val com.siesque.plantos.proto.admin.v1.ModuleUpdateOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

