// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializemodule")
public inline fun module(block: com.siesque.plantos.proto.admin.v1.ModuleKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.Module =
  com.siesque.plantos.proto.admin.v1.ModuleKt.Dsl._create(com.siesque.plantos.proto.admin.v1.Module.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.Module`
 */
public object ModuleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.Module.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.Module.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.Module = _builder.build()

    /**
     * `int32 id = 1;`
     */
    public var id: kotlin.Int
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `int32 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `.plantos.admin.v1.Status status = 3;`
     */
    public var status: com.siesque.plantos.proto.admin.v1.Status
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.plantos.admin.v1.Status status = 3;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * ```
     * Battery percentage 0-100
     * ```
     *
     * `float battery_level = 4;`
     */
    public var batteryLevel: kotlin.Float
      @kotlin.jvm.JvmName("getBatteryLevel")
        get() = _builder.batteryLevel
      @kotlin.jvm.JvmName("setBatteryLevel")
        set(value) {
        _builder.batteryLevel = value
      }
    /**
     * ```
     * Battery percentage 0-100
     * ```
     *
     * `float battery_level = 4;`
     */
    public fun clearBatteryLevel() {
      _builder.clearBatteryLevel()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ZoneIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * IDs of zones controlled by this module
     * ```
     *
     * `repeated int32 zone_ids = 5;`
     */
     public val zoneIds: com.google.protobuf.kotlin.DslList<kotlin.Int, ZoneIdsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.zoneIdsList
      )
    /**
     * ```
     * IDs of zones controlled by this module
     * ```
     *
     * `repeated int32 zone_ids = 5;`
     * @param value The zoneIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addZoneIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, ZoneIdsProxy>.add(value: kotlin.Int) {
      _builder.addZoneIds(value)
    }/**
     * ```
     * IDs of zones controlled by this module
     * ```
     *
     * `repeated int32 zone_ids = 5;`
     * @param value The zoneIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignZoneIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, ZoneIdsProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * ```
     * IDs of zones controlled by this module
     * ```
     *
     * `repeated int32 zone_ids = 5;`
     * @param values The zoneIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllZoneIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, ZoneIdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllZoneIds(values)
    }/**
     * ```
     * IDs of zones controlled by this module
     * ```
     *
     * `repeated int32 zone_ids = 5;`
     * @param values The zoneIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllZoneIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, ZoneIdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * ```
     * IDs of zones controlled by this module
     * ```
     *
     * `repeated int32 zone_ids = 5;`
     * @param index The index to set the value at.
     * @param value The zoneIds to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setZoneIds")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, ZoneIdsProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setZoneIds(index, value)
    }/**
     * ```
     * IDs of zones controlled by this module
     * ```
     *
     * `repeated int32 zone_ids = 5;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearZoneIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, ZoneIdsProxy>.clear() {
      _builder.clearZoneIds()
    }
    /**
     * ```
     * Last time module was seen
     * ```
     *
     * `.google.protobuf.Timestamp last_seen = 6;`
     */
    public var lastSeen: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getLastSeen")
        get() = _builder.lastSeen
      @kotlin.jvm.JvmName("setLastSeen")
        set(value) {
        _builder.lastSeen = value
      }
    /**
     * ```
     * Last time module was seen
     * ```
     *
     * `.google.protobuf.Timestamp last_seen = 6;`
     */
    public fun clearLastSeen() {
      _builder.clearLastSeen()
    }
    /**
     * ```
     * Last time module was seen
     * ```
     *
     * `.google.protobuf.Timestamp last_seen = 6;`
     * @return Whether the lastSeen field is set.
     */
    public fun hasLastSeen(): kotlin.Boolean {
      return _builder.hasLastSeen()
    }

    public val ModuleKt.Dsl.lastSeenOrNull: com.google.protobuf.Timestamp?
      get() = _builder.lastSeenOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.Module.copy(block: `com.siesque.plantos.proto.admin.v1`.ModuleKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.Module =
  `com.siesque.plantos.proto.admin.v1`.ModuleKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.ModuleOrBuilder.lastSeenOrNull: com.google.protobuf.Timestamp?
  get() = if (hasLastSeen()) getLastSeen() else null

