// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializepauseZoneResponse")
public inline fun pauseZoneResponse(block: com.siesque.plantos.proto.admin.v1.PauseZoneResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.PauseZoneResponse =
  com.siesque.plantos.proto.admin.v1.PauseZoneResponseKt.Dsl._create(com.siesque.plantos.proto.admin.v1.PauseZoneResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.PauseZoneResponse`
 */
public object PauseZoneResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.PauseZoneResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.PauseZoneResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.PauseZoneResponse = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * `.plantos.admin.v1.Status previous_status = 2;`
     */
    public var previousStatus: com.siesque.plantos.proto.admin.v1.Status
      @kotlin.jvm.JvmName("getPreviousStatus")
        get() = _builder.previousStatus
      @kotlin.jvm.JvmName("setPreviousStatus")
        set(value) {
        _builder.previousStatus = value
      }
    public var previousStatusValue: kotlin.Int
      @kotlin.jvm.JvmName("getPreviousStatusValue")
        get() = _builder.previousStatusValue
      @kotlin.jvm.JvmName("setPreviousStatusValue")
        set(value) {
        _builder.previousStatusValue = value
      }
    /**
     * `.plantos.admin.v1.Status previous_status = 2;`
     */
    public fun clearPreviousStatus() {
      _builder.clearPreviousStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.PauseZoneResponse.copy(block: `com.siesque.plantos.proto.admin.v1`.PauseZoneResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.PauseZoneResponse =
  `com.siesque.plantos.proto.admin.v1`.PauseZoneResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

