// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializeresumeZoneResponse")
public inline fun resumeZoneResponse(block: com.siesque.plantos.proto.admin.v1.ResumeZoneResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ResumeZoneResponse =
  com.siesque.plantos.proto.admin.v1.ResumeZoneResponseKt.Dsl._create(com.siesque.plantos.proto.admin.v1.ResumeZoneResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.ResumeZoneResponse`
 */
public object ResumeZoneResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.ResumeZoneResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.ResumeZoneResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.ResumeZoneResponse = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.ResumeZoneResponse.copy(block: `com.siesque.plantos.proto.admin.v1`.ResumeZoneResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ResumeZoneResponse =
  `com.siesque.plantos.proto.admin.v1`.ResumeZoneResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

