// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializestatisticsUpdate")
public inline fun statisticsUpdate(block: com.siesque.plantos.proto.admin.v1.StatisticsUpdateKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.StatisticsUpdate =
  com.siesque.plantos.proto.admin.v1.StatisticsUpdateKt.Dsl._create(com.siesque.plantos.proto.admin.v1.StatisticsUpdate.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.StatisticsUpdate`
 */
public object StatisticsUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.StatisticsUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.StatisticsUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.StatisticsUpdate = _builder.build()

    /**
     * `int32 zone_id = 1;`
     */
    public var zoneId: kotlin.Int
      @kotlin.jvm.JvmName("getZoneId")
        get() = _builder.zoneId
      @kotlin.jvm.JvmName("setZoneId")
        set(value) {
        _builder.zoneId = value
      }
    /**
     * `int32 zone_id = 1;`
     */
    public fun clearZoneId() {
      _builder.clearZoneId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UpdatedStatisticsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .plantos.admin.v1.Statistic updated_statistics = 2;`
     */
     public val updatedStatistics: com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, UpdatedStatisticsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.updatedStatisticsList
      )
    /**
     * `repeated .plantos.admin.v1.Statistic updated_statistics = 2;`
     * @param value The updatedStatistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addUpdatedStatistics")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, UpdatedStatisticsProxy>.add(value: com.siesque.plantos.proto.admin.v1.Statistic) {
      _builder.addUpdatedStatistics(value)
    }
    /**
     * `repeated .plantos.admin.v1.Statistic updated_statistics = 2;`
     * @param value The updatedStatistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignUpdatedStatistics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, UpdatedStatisticsProxy>.plusAssign(value: com.siesque.plantos.proto.admin.v1.Statistic) {
      add(value)
    }
    /**
     * `repeated .plantos.admin.v1.Statistic updated_statistics = 2;`
     * @param values The updatedStatistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllUpdatedStatistics")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, UpdatedStatisticsProxy>.addAll(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.Statistic>) {
      _builder.addAllUpdatedStatistics(values)
    }
    /**
     * `repeated .plantos.admin.v1.Statistic updated_statistics = 2;`
     * @param values The updatedStatistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllUpdatedStatistics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, UpdatedStatisticsProxy>.plusAssign(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.Statistic>) {
      addAll(values)
    }
    /**
     * `repeated .plantos.admin.v1.Statistic updated_statistics = 2;`
     * @param index The index to set the value at.
     * @param value The updatedStatistics to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setUpdatedStatistics")
    public operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, UpdatedStatisticsProxy>.set(index: kotlin.Int, value: com.siesque.plantos.proto.admin.v1.Statistic) {
      _builder.setUpdatedStatistics(index, value)
    }
    /**
     * `repeated .plantos.admin.v1.Statistic updated_statistics = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearUpdatedStatistics")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, UpdatedStatisticsProxy>.clear() {
      _builder.clearUpdatedStatistics()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val StatisticsUpdateKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.StatisticsUpdate.copy(block: `com.siesque.plantos.proto.admin.v1`.StatisticsUpdateKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.StatisticsUpdate =
  `com.siesque.plantos.proto.admin.v1`.StatisticsUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.StatisticsUpdateOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

