// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializestatistic")
public inline fun statistic(block: com.siesque.plantos.proto.admin.v1.StatisticKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.Statistic =
  com.siesque.plantos.proto.admin.v1.StatisticKt.Dsl._create(com.siesque.plantos.proto.admin.v1.Statistic.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.Statistic`
 */
public object StatisticKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.Statistic.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.Statistic.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.Statistic = _builder.build()

    /**
     * `.plantos.admin.v1.StatisticType type = 1;`
     */
    public var type: com.siesque.plantos.proto.admin.v1.StatisticType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeValue")
        get() = _builder.typeValue
      @kotlin.jvm.JvmName("setTypeValue")
        set(value) {
        _builder.typeValue = value
      }
    /**
     * `.plantos.admin.v1.StatisticType type = 1;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class HistoryProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .plantos.admin.v1.StatisticDataPoint history = 2;`
     */
     public val history: com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticDataPoint, HistoryProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.historyList
      )
    /**
     * `repeated .plantos.admin.v1.StatisticDataPoint history = 2;`
     * @param value The history to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addHistory")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticDataPoint, HistoryProxy>.add(value: com.siesque.plantos.proto.admin.v1.StatisticDataPoint) {
      _builder.addHistory(value)
    }
    /**
     * `repeated .plantos.admin.v1.StatisticDataPoint history = 2;`
     * @param value The history to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignHistory")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticDataPoint, HistoryProxy>.plusAssign(value: com.siesque.plantos.proto.admin.v1.StatisticDataPoint) {
      add(value)
    }
    /**
     * `repeated .plantos.admin.v1.StatisticDataPoint history = 2;`
     * @param values The history to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllHistory")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticDataPoint, HistoryProxy>.addAll(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.StatisticDataPoint>) {
      _builder.addAllHistory(values)
    }
    /**
     * `repeated .plantos.admin.v1.StatisticDataPoint history = 2;`
     * @param values The history to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllHistory")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticDataPoint, HistoryProxy>.plusAssign(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.StatisticDataPoint>) {
      addAll(values)
    }
    /**
     * `repeated .plantos.admin.v1.StatisticDataPoint history = 2;`
     * @param index The index to set the value at.
     * @param value The history to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setHistory")
    public operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticDataPoint, HistoryProxy>.set(index: kotlin.Int, value: com.siesque.plantos.proto.admin.v1.StatisticDataPoint) {
      _builder.setHistory(index, value)
    }
    /**
     * `repeated .plantos.admin.v1.StatisticDataPoint history = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearHistory")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.StatisticDataPoint, HistoryProxy>.clear() {
      _builder.clearHistory()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.Statistic.copy(block: `com.siesque.plantos.proto.admin.v1`.StatisticKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.Statistic =
  `com.siesque.plantos.proto.admin.v1`.StatisticKt.Dsl._create(this.toBuilder()).apply { block() }._build()

