// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializeupdateZoneSettingsResponse")
public inline fun updateZoneSettingsResponse(block: com.siesque.plantos.proto.admin.v1.UpdateZoneSettingsResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.UpdateZoneSettingsResponse =
  com.siesque.plantos.proto.admin.v1.UpdateZoneSettingsResponseKt.Dsl._create(com.siesque.plantos.proto.admin.v1.UpdateZoneSettingsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.UpdateZoneSettingsResponse`
 */
public object UpdateZoneSettingsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.UpdateZoneSettingsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.UpdateZoneSettingsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.UpdateZoneSettingsResponse = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * `.plantos.admin.v1.ZoneSettings updated_settings = 2;`
     */
    public var updatedSettings: com.siesque.plantos.proto.admin.v1.ZoneSettings
      @kotlin.jvm.JvmName("getUpdatedSettings")
        get() = _builder.updatedSettings
      @kotlin.jvm.JvmName("setUpdatedSettings")
        set(value) {
        _builder.updatedSettings = value
      }
    /**
     * `.plantos.admin.v1.ZoneSettings updated_settings = 2;`
     */
    public fun clearUpdatedSettings() {
      _builder.clearUpdatedSettings()
    }
    /**
     * `.plantos.admin.v1.ZoneSettings updated_settings = 2;`
     * @return Whether the updatedSettings field is set.
     */
    public fun hasUpdatedSettings(): kotlin.Boolean {
      return _builder.hasUpdatedSettings()
    }

    public val UpdateZoneSettingsResponseKt.Dsl.updatedSettingsOrNull: com.siesque.plantos.proto.admin.v1.ZoneSettings?
      get() = _builder.updatedSettingsOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.UpdateZoneSettingsResponse.copy(block: `com.siesque.plantos.proto.admin.v1`.UpdateZoneSettingsResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.UpdateZoneSettingsResponse =
  `com.siesque.plantos.proto.admin.v1`.UpdateZoneSettingsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.UpdateZoneSettingsResponseOrBuilder.updatedSettingsOrNull: com.siesque.plantos.proto.admin.v1.ZoneSettings?
  get() = if (hasUpdatedSettings()) getUpdatedSettings() else null

