// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializewaterZoneRequest")
public inline fun waterZoneRequest(block: com.siesque.plantos.proto.admin.v1.WaterZoneRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.WaterZoneRequest =
  com.siesque.plantos.proto.admin.v1.WaterZoneRequestKt.Dsl._create(com.siesque.plantos.proto.admin.v1.WaterZoneRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.WaterZoneRequest`
 */
public object WaterZoneRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.WaterZoneRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.WaterZoneRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.WaterZoneRequest = _builder.build()

    /**
     * `int32 zone_id = 1;`
     */
    public var zoneId: kotlin.Int
      @kotlin.jvm.JvmName("getZoneId")
        get() = _builder.zoneId
      @kotlin.jvm.JvmName("setZoneId")
        set(value) {
        _builder.zoneId = value
      }
    /**
     * `int32 zone_id = 1;`
     */
    public fun clearZoneId() {
      _builder.clearZoneId()
    }

    /**
     * ```
     * Optional: override default duration
     * ```
     *
     * `optional .google.protobuf.Duration duration = 2;`
     */
    public var duration: com.google.protobuf.Duration
      @kotlin.jvm.JvmName("getDuration")
        get() = _builder.duration
      @kotlin.jvm.JvmName("setDuration")
        set(value) {
        _builder.duration = value
      }
    /**
     * ```
     * Optional: override default duration
     * ```
     *
     * `optional .google.protobuf.Duration duration = 2;`
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }
    /**
     * ```
     * Optional: override default duration
     * ```
     *
     * `optional .google.protobuf.Duration duration = 2;`
     * @return Whether the duration field is set.
     */
    public fun hasDuration(): kotlin.Boolean {
      return _builder.hasDuration()
    }

    public val WaterZoneRequestKt.Dsl.durationOrNull: com.google.protobuf.Duration?
      get() = _builder.durationOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.WaterZoneRequest.copy(block: `com.siesque.plantos.proto.admin.v1`.WaterZoneRequestKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.WaterZoneRequest =
  `com.siesque.plantos.proto.admin.v1`.WaterZoneRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.WaterZoneRequestOrBuilder.durationOrNull: com.google.protobuf.Duration?
  get() = if (hasDuration()) getDuration() else null

