// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializewaterZoneResponse")
public inline fun waterZoneResponse(block: com.siesque.plantos.proto.admin.v1.WaterZoneResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.WaterZoneResponse =
  com.siesque.plantos.proto.admin.v1.WaterZoneResponseKt.Dsl._create(com.siesque.plantos.proto.admin.v1.WaterZoneResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.WaterZoneResponse`
 */
public object WaterZoneResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.WaterZoneResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.WaterZoneResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.WaterZoneResponse = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * `.google.protobuf.Timestamp started_at = 2;`
     */
    public var startedAt: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getStartedAt")
        get() = _builder.startedAt
      @kotlin.jvm.JvmName("setStartedAt")
        set(value) {
        _builder.startedAt = value
      }
    /**
     * `.google.protobuf.Timestamp started_at = 2;`
     */
    public fun clearStartedAt() {
      _builder.clearStartedAt()
    }
    /**
     * `.google.protobuf.Timestamp started_at = 2;`
     * @return Whether the startedAt field is set.
     */
    public fun hasStartedAt(): kotlin.Boolean {
      return _builder.hasStartedAt()
    }

    public val WaterZoneResponseKt.Dsl.startedAtOrNull: com.google.protobuf.Timestamp?
      get() = _builder.startedAtOrNull

    /**
     * `.google.protobuf.Duration duration = 3;`
     */
    public var duration: com.google.protobuf.Duration
      @kotlin.jvm.JvmName("getDuration")
        get() = _builder.duration
      @kotlin.jvm.JvmName("setDuration")
        set(value) {
        _builder.duration = value
      }
    /**
     * `.google.protobuf.Duration duration = 3;`
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }
    /**
     * `.google.protobuf.Duration duration = 3;`
     * @return Whether the duration field is set.
     */
    public fun hasDuration(): kotlin.Boolean {
      return _builder.hasDuration()
    }

    public val WaterZoneResponseKt.Dsl.durationOrNull: com.google.protobuf.Duration?
      get() = _builder.durationOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.WaterZoneResponse.copy(block: `com.siesque.plantos.proto.admin.v1`.WaterZoneResponseKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.WaterZoneResponse =
  `com.siesque.plantos.proto.admin.v1`.WaterZoneResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.WaterZoneResponseOrBuilder.startedAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasStartedAt()) getStartedAt() else null

public val com.siesque.plantos.proto.admin.v1.WaterZoneResponseOrBuilder.durationOrNull: com.google.protobuf.Duration?
  get() = if (hasDuration()) getDuration() else null

