// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializewelcome")
public inline fun welcome(block: com.siesque.plantos.proto.admin.v1.WelcomeKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.Welcome =
  com.siesque.plantos.proto.admin.v1.WelcomeKt.Dsl._create(com.siesque.plantos.proto.admin.v1.Welcome.newBuilder()).apply { block() }._build()
/**
 * ```
 * Hub -> Client: Handshake response
 * ```
 *
 * Protobuf type `plantos.admin.v1.Welcome`
 */
public object WelcomeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.Welcome.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.Welcome.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.Welcome = _builder.build()

    /**
     * `string hub_id = 1;`
     */
    public var hubId: kotlin.String
      @kotlin.jvm.JvmName("getHubId")
        get() = _builder.hubId
      @kotlin.jvm.JvmName("setHubId")
        set(value) {
        _builder.hubId = value
      }
    /**
     * `string hub_id = 1;`
     */
    public fun clearHubId() {
      _builder.clearHubId()
    }

    /**
     * `string hub_version = 2;`
     */
    public var hubVersion: kotlin.String
      @kotlin.jvm.JvmName("getHubVersion")
        get() = _builder.hubVersion
      @kotlin.jvm.JvmName("setHubVersion")
        set(value) {
        _builder.hubVersion = value
      }
    /**
     * `string hub_version = 2;`
     */
    public fun clearHubVersion() {
      _builder.clearHubVersion()
    }

    /**
     * ```
     * Unix timestamp for sync
     * ```
     *
     * `int64 server_timestamp = 3;`
     */
    public var serverTimestamp: kotlin.Long
      @kotlin.jvm.JvmName("getServerTimestamp")
        get() = _builder.serverTimestamp
      @kotlin.jvm.JvmName("setServerTimestamp")
        set(value) {
        _builder.serverTimestamp = value
      }
    /**
     * ```
     * Unix timestamp for sync
     * ```
     *
     * `int64 server_timestamp = 3;`
     */
    public fun clearServerTimestamp() {
      _builder.clearServerTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.Welcome.copy(block: `com.siesque.plantos.proto.admin.v1`.WelcomeKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.Welcome =
  `com.siesque.plantos.proto.admin.v1`.WelcomeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

