// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializezone")
public inline fun zone(block: com.siesque.plantos.proto.admin.v1.ZoneKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.Zone =
  com.siesque.plantos.proto.admin.v1.ZoneKt.Dsl._create(com.siesque.plantos.proto.admin.v1.Zone.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.Zone`
 */
public object ZoneKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.Zone.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.Zone.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.Zone = _builder.build()

    /**
     * `int32 id = 1;`
     */
    public var id: kotlin.Int
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `int32 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * ID of the controlling module
     * ```
     *
     * `int32 module_id = 2;`
     */
    public var moduleId: kotlin.Int
      @kotlin.jvm.JvmName("getModuleId")
        get() = _builder.moduleId
      @kotlin.jvm.JvmName("setModuleId")
        set(value) {
        _builder.moduleId = value
      }
    /**
     * ```
     * ID of the controlling module
     * ```
     *
     * `int32 module_id = 2;`
     */
    public fun clearModuleId() {
      _builder.clearModuleId()
    }

    /**
     * `string name = 3;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 3;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * Unicode emoji or icon identifier
     * ```
     *
     * `string icon = 4;`
     */
    public var icon: kotlin.String
      @kotlin.jvm.JvmName("getIcon")
        get() = _builder.icon
      @kotlin.jvm.JvmName("setIcon")
        set(value) {
        _builder.icon = value
      }
    /**
     * ```
     * Unicode emoji or icon identifier
     * ```
     *
     * `string icon = 4;`
     */
    public fun clearIcon() {
      _builder.clearIcon()
    }

    /**
     * `.plantos.admin.v1.Status status = 5;`
     */
    public var status: com.siesque.plantos.proto.admin.v1.Status
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.plantos.admin.v1.Status status = 5;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.google.protobuf.Timestamp last_watered = 6;`
     */
    public var lastWatered: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getLastWatered")
        get() = _builder.lastWatered
      @kotlin.jvm.JvmName("setLastWatered")
        set(value) {
        _builder.lastWatered = value
      }
    /**
     * `.google.protobuf.Timestamp last_watered = 6;`
     */
    public fun clearLastWatered() {
      _builder.clearLastWatered()
    }
    /**
     * `.google.protobuf.Timestamp last_watered = 6;`
     * @return Whether the lastWatered field is set.
     */
    public fun hasLastWatered(): kotlin.Boolean {
      return _builder.hasLastWatered()
    }

    public val ZoneKt.Dsl.lastWateredOrNull: com.google.protobuf.Timestamp?
      get() = _builder.lastWateredOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CurrentStatisticsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Current values only (not full history)
     * ```
     *
     * `repeated .plantos.admin.v1.Statistic current_statistics = 7;`
     */
     public val currentStatistics: com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, CurrentStatisticsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.currentStatisticsList
      )
    /**
     * ```
     * Current values only (not full history)
     * ```
     *
     * `repeated .plantos.admin.v1.Statistic current_statistics = 7;`
     * @param value The currentStatistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addCurrentStatistics")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, CurrentStatisticsProxy>.add(value: com.siesque.plantos.proto.admin.v1.Statistic) {
      _builder.addCurrentStatistics(value)
    }
    /**
     * ```
     * Current values only (not full history)
     * ```
     *
     * `repeated .plantos.admin.v1.Statistic current_statistics = 7;`
     * @param value The currentStatistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignCurrentStatistics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, CurrentStatisticsProxy>.plusAssign(value: com.siesque.plantos.proto.admin.v1.Statistic) {
      add(value)
    }
    /**
     * ```
     * Current values only (not full history)
     * ```
     *
     * `repeated .plantos.admin.v1.Statistic current_statistics = 7;`
     * @param values The currentStatistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllCurrentStatistics")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, CurrentStatisticsProxy>.addAll(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.Statistic>) {
      _builder.addAllCurrentStatistics(values)
    }
    /**
     * ```
     * Current values only (not full history)
     * ```
     *
     * `repeated .plantos.admin.v1.Statistic current_statistics = 7;`
     * @param values The currentStatistics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllCurrentStatistics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, CurrentStatisticsProxy>.plusAssign(values: kotlin.collections.Iterable<com.siesque.plantos.proto.admin.v1.Statistic>) {
      addAll(values)
    }
    /**
     * ```
     * Current values only (not full history)
     * ```
     *
     * `repeated .plantos.admin.v1.Statistic current_statistics = 7;`
     * @param index The index to set the value at.
     * @param value The currentStatistics to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setCurrentStatistics")
    public operator fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, CurrentStatisticsProxy>.set(index: kotlin.Int, value: com.siesque.plantos.proto.admin.v1.Statistic) {
      _builder.setCurrentStatistics(index, value)
    }
    /**
     * ```
     * Current values only (not full history)
     * ```
     *
     * `repeated .plantos.admin.v1.Statistic current_statistics = 7;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearCurrentStatistics")
    public fun com.google.protobuf.kotlin.DslList<com.siesque.plantos.proto.admin.v1.Statistic, CurrentStatisticsProxy>.clear() {
      _builder.clearCurrentStatistics()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.Zone.copy(block: `com.siesque.plantos.proto.admin.v1`.ZoneKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.Zone =
  `com.siesque.plantos.proto.admin.v1`.ZoneKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.ZoneOrBuilder.lastWateredOrNull: com.google.protobuf.Timestamp?
  get() = if (hasLastWatered()) getLastWatered() else null

