// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializezoneUpdate")
public inline fun zoneUpdate(block: com.siesque.plantos.proto.admin.v1.ZoneUpdateKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ZoneUpdate =
  com.siesque.plantos.proto.admin.v1.ZoneUpdateKt.Dsl._create(com.siesque.plantos.proto.admin.v1.ZoneUpdate.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.ZoneUpdate`
 */
public object ZoneUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.ZoneUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.ZoneUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.ZoneUpdate = _builder.build()

    /**
     * `int32 zone_id = 1;`
     */
    public var zoneId: kotlin.Int
      @kotlin.jvm.JvmName("getZoneId")
        get() = _builder.zoneId
      @kotlin.jvm.JvmName("setZoneId")
        set(value) {
        _builder.zoneId = value
      }
    /**
     * `int32 zone_id = 1;`
     */
    public fun clearZoneId() {
      _builder.clearZoneId()
    }

    /**
     * `.plantos.admin.v1.Zone zone = 2;`
     */
    public var zone: com.siesque.plantos.proto.admin.v1.Zone
      @kotlin.jvm.JvmName("getZone")
        get() = _builder.zone
      @kotlin.jvm.JvmName("setZone")
        set(value) {
        _builder.zone = value
      }
    /**
     * `.plantos.admin.v1.Zone zone = 2;`
     */
    public fun clearZone() {
      _builder.clearZone()
    }
    /**
     * `.plantos.admin.v1.Zone zone = 2;`
     * @return Whether the zone field is set.
     */
    public fun hasZone(): kotlin.Boolean {
      return _builder.hasZone()
    }

    public val ZoneUpdateKt.Dsl.zoneOrNull: com.siesque.plantos.proto.admin.v1.Zone?
      get() = _builder.zoneOrNull

    /**
     * `.plantos.admin.v1.ZoneUpdate.ChangeType change_type = 3;`
     */
    public var changeType: com.siesque.plantos.proto.admin.v1.ZoneUpdate.ChangeType
      @kotlin.jvm.JvmName("getChangeType")
        get() = _builder.changeType
      @kotlin.jvm.JvmName("setChangeType")
        set(value) {
        _builder.changeType = value
      }
    public var changeTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getChangeTypeValue")
        get() = _builder.changeTypeValue
      @kotlin.jvm.JvmName("setChangeTypeValue")
        set(value) {
        _builder.changeTypeValue = value
      }
    /**
     * `.plantos.admin.v1.ZoneUpdate.ChangeType change_type = 3;`
     */
    public fun clearChangeType() {
      _builder.clearChangeType()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 4;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 4;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 4;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val ZoneUpdateKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.ZoneUpdate.copy(block: `com.siesque.plantos.proto.admin.v1`.ZoneUpdateKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ZoneUpdate =
  `com.siesque.plantos.proto.admin.v1`.ZoneUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.ZoneUpdateOrBuilder.zoneOrNull: com.siesque.plantos.proto.admin.v1.Zone?
  get() = if (hasZone()) getZone() else null

public val com.siesque.plantos.proto.admin.v1.ZoneUpdateOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

