// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin/v1/admin.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.siesque.plantos.proto.admin.v1;

@kotlin.jvm.JvmName("-initializezoneSettings")
public inline fun zoneSettings(block: com.siesque.plantos.proto.admin.v1.ZoneSettingsKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ZoneSettings =
  com.siesque.plantos.proto.admin.v1.ZoneSettingsKt.Dsl._create(com.siesque.plantos.proto.admin.v1.ZoneSettings.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `plantos.admin.v1.ZoneSettings`
 */
public object ZoneSettingsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.siesque.plantos.proto.admin.v1.ZoneSettings.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.siesque.plantos.proto.admin.v1.ZoneSettings.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.siesque.plantos.proto.admin.v1.ZoneSettings = _builder.build()

    /**
     * `int32 zone_id = 1;`
     */
    public var zoneId: kotlin.Int
      @kotlin.jvm.JvmName("getZoneId")
        get() = _builder.zoneId
      @kotlin.jvm.JvmName("setZoneId")
        set(value) {
        _builder.zoneId = value
      }
    /**
     * `int32 zone_id = 1;`
     */
    public fun clearZoneId() {
      _builder.clearZoneId()
    }

    /**
     * `.plantos.admin.v1.ZoneSettings.Thresholds thresholds = 2;`
     */
    public var thresholds: com.siesque.plantos.proto.admin.v1.ZoneSettings.Thresholds
      @kotlin.jvm.JvmName("getThresholds")
        get() = _builder.thresholds
      @kotlin.jvm.JvmName("setThresholds")
        set(value) {
        _builder.thresholds = value
      }
    /**
     * `.plantos.admin.v1.ZoneSettings.Thresholds thresholds = 2;`
     */
    public fun clearThresholds() {
      _builder.clearThresholds()
    }
    /**
     * `.plantos.admin.v1.ZoneSettings.Thresholds thresholds = 2;`
     * @return Whether the thresholds field is set.
     */
    public fun hasThresholds(): kotlin.Boolean {
      return _builder.hasThresholds()
    }

    public val ZoneSettingsKt.Dsl.thresholdsOrNull: com.siesque.plantos.proto.admin.v1.ZoneSettings.Thresholds?
      get() = _builder.thresholdsOrNull

    /**
     * ```
     * Notification settings
     * ```
     *
     * `bool notify_on_error = 3;`
     */
    public var notifyOnError: kotlin.Boolean
      @kotlin.jvm.JvmName("getNotifyOnError")
        get() = _builder.notifyOnError
      @kotlin.jvm.JvmName("setNotifyOnError")
        set(value) {
        _builder.notifyOnError = value
      }
    /**
     * ```
     * Notification settings
     * ```
     *
     * `bool notify_on_error = 3;`
     */
    public fun clearNotifyOnError() {
      _builder.clearNotifyOnError()
    }

    /**
     * `bool notify_on_low_battery = 4;`
     */
    public var notifyOnLowBattery: kotlin.Boolean
      @kotlin.jvm.JvmName("getNotifyOnLowBattery")
        get() = _builder.notifyOnLowBattery
      @kotlin.jvm.JvmName("setNotifyOnLowBattery")
        set(value) {
        _builder.notifyOnLowBattery = value
      }
    /**
     * `bool notify_on_low_battery = 4;`
     */
    public fun clearNotifyOnLowBattery() {
      _builder.clearNotifyOnLowBattery()
    }
  }
  @kotlin.jvm.JvmName("-initializethresholds")
  public inline fun thresholds(block: com.siesque.plantos.proto.admin.v1.ZoneSettingsKt.ThresholdsKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ZoneSettings.Thresholds =
    com.siesque.plantos.proto.admin.v1.ZoneSettingsKt.ThresholdsKt.Dsl._create(com.siesque.plantos.proto.admin.v1.ZoneSettings.Thresholds.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Thresholds for alerts
   * ```
   *
   * Protobuf type `plantos.admin.v1.ZoneSettings.Thresholds`
   */
  public object ThresholdsKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.siesque.plantos.proto.admin.v1.ZoneSettings.Thresholds.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: com.siesque.plantos.proto.admin.v1.ZoneSettings.Thresholds.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): com.siesque.plantos.proto.admin.v1.ZoneSettings.Thresholds = _builder.build()

      /**
       * ```
       * Celsius
       * ```
       *
       * `float min_temperature = 1;`
       */
      public var minTemperature: kotlin.Float
        @kotlin.jvm.JvmName("getMinTemperature")
          get() = _builder.minTemperature
        @kotlin.jvm.JvmName("setMinTemperature")
          set(value) {
          _builder.minTemperature = value
        }
      /**
       * ```
       * Celsius
       * ```
       *
       * `float min_temperature = 1;`
       */
      public fun clearMinTemperature() {
        _builder.clearMinTemperature()
      }

      /**
       * ```
       * Celsius
       * ```
       *
       * `float max_temperature = 2;`
       */
      public var maxTemperature: kotlin.Float
        @kotlin.jvm.JvmName("getMaxTemperature")
          get() = _builder.maxTemperature
        @kotlin.jvm.JvmName("setMaxTemperature")
          set(value) {
          _builder.maxTemperature = value
        }
      /**
       * ```
       * Celsius
       * ```
       *
       * `float max_temperature = 2;`
       */
      public fun clearMaxTemperature() {
        _builder.clearMaxTemperature()
      }

      /**
       * ```
       * Percentage
       * ```
       *
       * `float min_soil_moisture = 3;`
       */
      public var minSoilMoisture: kotlin.Float
        @kotlin.jvm.JvmName("getMinSoilMoisture")
          get() = _builder.minSoilMoisture
        @kotlin.jvm.JvmName("setMinSoilMoisture")
          set(value) {
          _builder.minSoilMoisture = value
        }
      /**
       * ```
       * Percentage
       * ```
       *
       * `float min_soil_moisture = 3;`
       */
      public fun clearMinSoilMoisture() {
        _builder.clearMinSoilMoisture()
      }

      /**
       * ```
       * Percentage
       * ```
       *
       * `float max_soil_moisture = 4;`
       */
      public var maxSoilMoisture: kotlin.Float
        @kotlin.jvm.JvmName("getMaxSoilMoisture")
          get() = _builder.maxSoilMoisture
        @kotlin.jvm.JvmName("setMaxSoilMoisture")
          set(value) {
          _builder.maxSoilMoisture = value
        }
      /**
       * ```
       * Percentage
       * ```
       *
       * `float max_soil_moisture = 4;`
       */
      public fun clearMaxSoilMoisture() {
        _builder.clearMaxSoilMoisture()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.ZoneSettings.copy(block: `com.siesque.plantos.proto.admin.v1`.ZoneSettingsKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ZoneSettings =
  `com.siesque.plantos.proto.admin.v1`.ZoneSettingsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.siesque.plantos.proto.admin.v1.ZoneSettings.Thresholds.copy(block: `com.siesque.plantos.proto.admin.v1`.ZoneSettingsKt.ThresholdsKt.Dsl.() -> kotlin.Unit): com.siesque.plantos.proto.admin.v1.ZoneSettings.Thresholds =
  `com.siesque.plantos.proto.admin.v1`.ZoneSettingsKt.ThresholdsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.siesque.plantos.proto.admin.v1.ZoneSettingsOrBuilder.thresholdsOrNull: com.siesque.plantos.proto.admin.v1.ZoneSettings.Thresholds?
  get() = if (hasThresholds()) getThresholds() else null

