name: Android Setup
description: Shared setup steps for Android CI jobs

inputs:
  java-version:
    description: Java version to use
    required: false
    default: "21"
  distribution:
    description: Java distribution
    required: false
    default: "temurin"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
